fix yaml

diff --git a/task/validate-fbc/0.2/validate-fbc.yaml b/task/validate-fbc/0.2/validate-fbc.yaml
--- a/task/validate-fbc/0.2/validate-fbc.yaml
+++ b/task/validate-fbc/0.2/validate-fbc.yaml
@@ -5,7 +5,7 @@ apiVersion: tekton.dev/v1
 kind: Task
 metadata:
   labels:
-    app.kubernetes.io/version: "0.1"
+    app.kubernetes.io/version: "0.2"
   annotations:
     tekton.dev/pipelines.minVersion: "0.12.1"
     tekton.dev/tags: "konflux"
@@ -197,7 +197,7 @@ spec:
             echo -n "$OCP_VERSION_FROM_LABEL" > /shared/ocp_versions_from_label
 
         else
-            CLEAN_VER=$(echo "$OCP_VERSION" | sed 's/^v//')
+            CLEAN_VER="${OCP_VERSION#v}"
 
             SKIP_BASE_IMAGE_CHECK=false
             OCP_VERSIONS_FROM_BASE="$CLEAN_VER"
@@ -268,7 +268,6 @@ spec:
         image_with_digest=$(cat /shared/image_with_digest)
 
         # read the saved version of ocp if it exists
-        
         OCP_VERSIONS=""
         if [ -f /shared/ocp_versions_from_label ]; then
             # OCP version label exists (skip base check)
@@ -367,14 +366,14 @@ spec:
             echo "!ERROR! - Required binary /usr/bin/$OPM_BIN not found."
             echo "Available opm binaries in /usr/bin:"
             ls -l /usr/bin/opm*
-            
+
             note="Step extract-and-validate failed: Required OPM binary ($OPM_BIN) was not found. Check task logs for available versions."
             ERROR_OUTPUT=$(make_result_json -r ERROR -t "$note")
             echo "${ERROR_OUTPUT}" | tee "$(results.TEST_OUTPUT.path)"
             exit 0
           fi
         done
-        
+
         # Set highest OPM versoin as default to verify if FBC can de rendered successfully
         HIGHEST_OPM_VERSION=$(echo "$UNIQUE_OPM_VERSIONS" | tail -n1)
         echo "Default opm version set to: $HIGHEST_OPM_VERSION"
@@ -488,65 +487,63 @@ spec:
         # Entire range is either <v4.17 or >= v4.17
         else
             echo "Consistent range detected. Validating against MAX version ($MAX_VER) only."
-            CHECK_LIST="$MAX_VER"
+        fi
 
+        # examines the highest target OCP version to derive the target OCP version
+        # assumes this is in the form
+        # image-path:[v]major-digits.minor-digits[@sha...]
+        # extracts major digits and filters out any leading alphabetic characters, for e.g. 'v4' --> '4'
+        OCP_VER_MAJOR=$(echo "${MAX_VER}" | cut -d '.' -f 1 | sed "s/^[a-zA-Z]*//")
+        OCP_VER_MINOR=$(echo "${MAX_VER}" | cut -d '.' -f 2)
 
-          # examines the highest target OCP version to derive the target OCP version
-          # assumes this is in the form
-          # image-path:[v]major-digits.minor-digits[@sha...]
-          # extracts major digits and filters out any leading alphabetic characters, for e.g. 'v4' --> '4'
-          OCP_VER_MAJOR=$(echo "${MAX_VER}" | cut -d '.' -f 1 | sed "s/^[a-zA-Z]*//")
-          OCP_VER_MINOR=$(echo "${MAX_VER}" | cut -d '.' -f 2)
+        RUN_OCP_VERSION_VALIDATION="false"
+        digits_regex='^[0-9]*$'
+        if [[ ${OCP_VER_MAJOR} =~ $digits_regex ]] && [[ ${OCP_VER_MINOR} =~ $digits_regex ]] ; then
+          RUN_OCP_VERSION_VALIDATION="true"
+        fi
 
-          RUN_OCP_VERSION_VALIDATION="false"
-          digits_regex='^[0-9]*$'
-          if [[ ${OCP_VER_MAJOR} =~ $digits_regex ]] && [[ ${OCP_VER_MINOR} =~ $digits_regex ]] ; then
-            RUN_OCP_VERSION_VALIDATION="true"
+        if [ "${RUN_OCP_VERSION_VALIDATION}" == "false" ] ; then
+          echo "!WARNING! - unable to assess bundle metadata alignment with OCP version because we cannot parse OCP version ${MAX_VER}"
+        else
+          OCP_BUNDLE_METADATA_THRESHOLD_MAJOR=4
+          OCP_BUNDLE_METADATA_THRESHOLD_MINOR=17
+          OCP_BUNDLE_METADATA_FORMAT="olm.bundle.object"
+
+          if [[ "${OCP_VER_MAJOR}" -ge "${OCP_BUNDLE_METADATA_THRESHOLD_MAJOR}" ]] && [[ "${OCP_VER_MINOR}" -ge "${OCP_BUNDLE_METADATA_THRESHOLD_MINOR}" ]]; then
+            OCP_BUNDLE_METADATA_FORMAT="olm.csv.metadata"
           fi
 
-          if [ "${RUN_OCP_VERSION_VALIDATION}" == "false" ] ; then
-            echo "!WARNING! - unable to assess bundle metadata alignment with OCP version because we cannot parse OCP version ${MAX_VER}"
+          # enforce the presence of either olm.csv.metadata or olm.bundle.object based on OCP version
+          if [[ "${OCP_BUNDLE_METADATA_FORMAT}" = "olm.csv.metadata" ]]; then
+            if ! jq -en 'reduce( inputs | select(.schema == "olm.bundle" and .properties[].type == "olm.bundle.object")) as $_ (0;.+1) == 0' ${OPM_RENDERED_CATALOG}; then
+              echo "!FAILURE! - olm.bundle.object bundle properties are not permitted in a FBC fragment for OCP version ${OCP_VER_MAJOR}.${OCP_VER_MINOR}. Fragments must move to olm.csv.metadata bundle metadata."
+              failure_num=$((failure_num + 1))
+              TESTPASSED=false
+            fi
           else
-            OCP_BUNDLE_METADATA_THRESHOLD_MAJOR=4
-            OCP_BUNDLE_METADATA_THRESHOLD_MINOR=17
-            OCP_BUNDLE_METADATA_FORMAT="olm.bundle.object"
-
-            if [[ "${OCP_VER_MAJOR}" -ge "${OCP_BUNDLE_METADATA_THRESHOLD_MAJOR}" ]] && [[ "${OCP_VER_MINOR}" -ge "${OCP_BUNDLE_METADATA_THRESHOLD_MINOR}" ]]; then
-              OCP_BUNDLE_METADATA_FORMAT="olm.csv.metadata"
-            fi
-
-            # enforce the presence of either olm.csv.metadata or olm.bundle.object based on OCP version
-            if [[ "${OCP_BUNDLE_METADATA_FORMAT}" = "olm.csv.metadata" ]]; then
-              if ! jq -en 'reduce( inputs | select(.schema == "olm.bundle" and .properties[].type == "olm.bundle.object")) as $_ (0;.+1) == 0' ${OPM_RENDERED_CATALOG}; then
-                echo "!FAILURE! - olm.bundle.object bundle properties are not permitted in a FBC fragment for OCP version ${OCP_VER_MAJOR}.${OCP_VER_MINOR}. Fragments must move to olm.csv.metadata bundle metadata."
-                failure_num=$((failure_num + 1))
-                TESTPASSED=false
-              fi
-            else
-              if ! jq -en 'reduce( inputs | select(.schema == "olm.bundle" and .properties[].type == "olm.csv.metadata")) as $_ (0;.+1) == 0' ${OPM_RENDERED_CATALOG}; then
-                echo "!FAILURE! - olm.csv.metadata bundle properties are not permitted in a FBC fragment for OCP version ${OCP_VER_MAJOR}.${OCP_VER_MINOR}. Fragments must only use olm.bundle.object bundle metadata."
-                failure_num=$((failure_num + 1))
-                TESTPASSED=false
-              fi
-            fi
-
-            # enforce that each bundle has the OCP-version-appropriate bundle metadata.
-            BUNDLE_COUNT=$(jq -en 'def count(stream): reduce stream as $i (0; .+1); count(inputs|select(.schema=="olm.bundle"))' ${OPM_RENDERED_CATALOG})
-            BUNDLE_BO_COUNT=$(jq -en 'def count(stream): reduce stream as $i (0; .+1); count(inputs|select(.schema == "olm.bundle" and .properties[].type == "olm.bundle.object"))' ${OPM_RENDERED_CATALOG})
-            BUNDLE_CM_COUNT=$(jq -en 'def count(stream): reduce stream as $i (0; .+1); count(inputs|select(.schema == "olm.bundle" and .properties[].type == "olm.csv.metadata"))' ${OPM_RENDERED_CATALOG})
-
-            if [[ "${OCP_BUNDLE_METADATA_FORMAT}" = "olm.csv.metadata" ]]; then
-              if [[ "${BUNDLE_COUNT}" -ne "${BUNDLE_CM_COUNT}" ]]; then
-                echo "!FAILURE! - every olm.bundle object in the fragment must have a corresponding olm.csv.metadata bundle property"
+            if ! jq -en 'reduce( inputs | select(.schema == "olm.bundle" and .properties[].type == "olm.csv.metadata")) as $_ (0;.+1) == 0' ${OPM_RENDERED_CATALOG}; then
+              echo "!FAILURE! - olm.csv.metadata bundle properties are not permitted in a FBC fragment for OCP version ${OCP_VER_MAJOR}.${OCP_VER_MINOR}. Fragments must only use olm.bundle.object bundle metadata."
               failure_num=$((failure_num + 1))
-                TESTPASSED=false
-              fi
-            else
-              if [[ "${BUNDLE_BO_COUNT}" -lt "${BUNDLE_COUNT}" ]]; then
-                echo "!FAILURE! - every olm.bundle object in the fragment must have at least one olm.bundle.object bundle property"
-              failure_num=$((failure_num + 1))
-                TESTPASSED=false
-              fi
+              TESTPASSED=false
+            fi
+          fi
+
+          # enforce that each bundle has the OCP-version-appropriate bundle metadata.
+          BUNDLE_COUNT=$(jq -en 'def count(stream): reduce stream as $i (0; .+1); count(inputs|select(.schema=="olm.bundle"))' ${OPM_RENDERED_CATALOG})
+          BUNDLE_BO_COUNT=$(jq -en 'def count(stream): reduce stream as $i (0; .+1); count(inputs|select(.schema == "olm.bundle" and .properties[].type == "olm.bundle.object"))' ${OPM_RENDERED_CATALOG})
+          BUNDLE_CM_COUNT=$(jq -en 'def count(stream): reduce stream as $i (0; .+1); count(inputs|select(.schema == "olm.bundle" and .properties[].type == "olm.csv.metadata"))' ${OPM_RENDERED_CATALOG})
+
+          if [[ "${OCP_BUNDLE_METADATA_FORMAT}" = "olm.csv.metadata" ]]; then
+            if [[ "${BUNDLE_COUNT}" -ne "${BUNDLE_CM_COUNT}" ]]; then
+              echo "!FAILURE! - every olm.bundle object in the fragment must have a corresponding olm.csv.metadata bundle property"
+            failure_num=$((failure_num + 1))
+              TESTPASSED=false
+            fi
+          else
+            if [[ "${BUNDLE_BO_COUNT}" -lt "${BUNDLE_COUNT}" ]]; then
+              echo "!FAILURE! - every olm.bundle object in the fragment must have at least one olm.bundle.object bundle property"
+            failure_num=$((failure_num + 1))
+              TESTPASSED=false
             fi
           fi
         fi
